version: 2.1

jobs:
  ci-engine:
    docker:
      - image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
    steps:
      - checkout
      - run:
          name: "Install Requirements"
          command: "pip install -r requirements.txt"
          working_directory: ./engine
      - run:
          name: "Train NLP Model"
          command: "python train.py"
          working_directory: ./engine
      - store_artifacts:
          path: ./engine/data.pth
  ci-api:
    docker:
      - image: maven:3.8-jdk-11
    steps:
      - checkout
      - run:
          name: "Build with Maven"
          command: "mvn clean package"
          working_directory: ./api
      - store_artifacts:
          path: ./api/target/*.jar
  ci-ui:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: "Install Node Modules"
          command: "npm install"
          working_directory: ./ui
      - run:
          name: "Build Vue Project"
          command: "npm run build"
          working_directory: ./ui

  deploy-gcloud:
    docker:
      - image: google/cloud-sdk
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

workflows:
  ci-jobs:
    jobs:
      - ci-api
      - ci-engine
      - ci-ui
  
  cd-dev:
    jobs:
      - deploy-gcloud:
          requires:
            - ci-engine
            - ci-api
            - ci-ui
          filters:
            branches:
              only:
                - master
